# A hello world sample
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-v1
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        version: v1
    spec:
      containers:
        - name: hello-world-v1
          image: anursek8s.azurecr.io/helloworld:v1
          ports:
            - name: http
              containerPort: 80
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: hello-world-v1-direct
spec:
  prefix: /services/helloworld/v1/
  service: hello-world-v1:80
  cors:
    origins: http://localhost:8080
    methods: POST, GET, OPTIONS
    headers: Content-Type
    credentials: true
    exposed_headers: X-Custom-Header
    max_age: "86400"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-v2
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
      version: v2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        version: v2
    spec:
      containers:
        - name: hello-world-v2
          image: anursek8s.azurecr.io/helloworld:v2
          ports:
            - name: http
              containerPort: 80
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: hello-world-v2-direct
spec:
  prefix: /services/helloworld/v2/
  service: hello-world-v2:80
